2025-10-11 18:28:36,635 : INFO : root : Loading config.
2025-10-11 18:28:36,639 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-11 18:28:36,639 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\f7776651e259183bd84a8c8d686bf868.mpf_cache
2025-10-11 18:28:36,731 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\70233839fc0b792ce11a62f3c18c1950.mpf_cache
2025-10-11 18:28:36,732 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-11 18:28:36,733 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\67a19b095f918111543419ac0271bfb1.mpf_cache
2025-10-11 18:28:36,734 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\be387b0e8ed00556ec738d83cd6947d1.mpf_cache
2025-10-11 18:28:36,734 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp7\modes\super_jets_setup\config\super_jets_setup.yaml
2025-10-11 18:28:36,734 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp7\modes\super_jets_setup\config\super_jets_setup.yaml.
2025-10-11 18:28:36,738 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp7\modes\super_jets_setup\config\super_jets_setup.yaml
2025-10-11 18:28:36,739 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\5a8efabd9666d8c71fa755fc28a9bf1e.mpf_cache
2025-10-11 18:28:36,740 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\fb58745e58584e219ff53db445e8e9f2.mpf_cache
2025-10-11 18:28:36,740 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b710dc01437f1dfd05f3b5275f67493b.mpf_cache
2025-10-11 18:28:36,741 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\0a23590f4081187a3ecee75c7657616e.mpf_cache
2025-10-11 18:28:36,742 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\374a5edaf0766cb9005f368df852c09d.mpf_cache
2025-10-11 18:28:36,743 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp7\modes\super_jets\shows\.\Super_Jets_on.yaml
2025-10-11 18:28:36,743 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp7\modes\super_jets\shows\.\Super_Jets_on.yaml.
2025-10-11 18:28:36,744 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp7\modes\super_jets\shows\.\Super_Jets_on.yaml
2025-10-11 18:28:36,744 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\069a726c379c7a3dc006889318eb30f2.mpf_cache
2025-10-11 18:28:36,745 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\6159dd3e8b071f5aa615e717784124e9.mpf_cache
2025-10-11 18:28:36,745 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-11 18:28:36,745 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-11-18-28-36-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-11 18:28:36,745 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-11 18:28:36,745 : INFO : Machine : Machine path: C:\Users\richa\ttp7
2025-10-11 18:28:36,745 : INFO : Machine : Platform: win32
2025-10-11 18:28:36,745 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-11 18:28:36,745 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-11 18:28:36,747 : INFO : Machine : Initializing MPF...
2025-10-11 18:28:37,209 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,266 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-11 18:28:37,266 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 1024400, 'prev_value': None, 'change': True}
2025-10-11 18:28:37,266 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,266 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,266 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-11 18:28:37,274 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-11 18:28:37,314 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough1>
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough2>
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough3>
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough4>
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>) <switch.s_trough5>
2025-10-11 18:28:37,315 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough6>
2025-10-11 18:28:37,320 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-10-11 18:28:37,322 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-10-11 18:28:39,349 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-10-11 18:28:39,349 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-10-11 18:28:39,704 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.0.dev10', 'prev_value': None, 'change': True}
2025-10-11 18:28:39,705 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.0.dev10 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0.dev19 or newer)', 'prev_value': None, 'change': True}
2025-10-11 18:28:39,706 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-10-11 18:28:39,790 : INFO : ball_device.bd_trough : State: idle
2025-10-11 18:28:39,791 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-10-11 18:28:39,791 : INFO : ball_device.bd_plunger : State: idle
2025-10-11 18:28:39,791 : INFO : ball_device.bd_left_scoop : BCH: Initial count: 0
2025-10-11 18:28:39,791 : INFO : ball_device.bd_left_scoop : State: idle
2025-10-11 18:28:39,792 : INFO : ball_device.bd_right_scoop : BCH: Initial count: 0
2025-10-11 18:28:39,792 : INFO : ball_device.bd_right_scoop : State: idle
2025-10-11 18:28:39,805 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-11 18:28:39,811 : ERROR : ConfigValidator : Your config contains a value for the setting "widgets:text:widgets:text:priority", but this is not a valid setting name.
2025-10-11 18:28:39,811 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 111, in process_widget
    self.machine.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Show "super_jets_startup" >> Failed to load config player super_jets_startup:slides with settings {'super_jets_startup': {'widgets': [{'type': 'text', 'text': 'SUPER JETS', 'font_size': 20, 'y': '60%', 'priority': 200, '_default_settings': ['type', 'text', 'font_size', 'y', 'priority']}], 'target': None, 'background_color': [0.0, 0.0, 0.0, 1.0], 'priority': None, 'show': True, 'force': False, 'expire': None, 'slide': None, 'tokens': {}, 'action': 'play'}} >> Your config contains a value for the setting "widgets:text:widgets:text:priority", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-11 18:28:39,814 : INFO : Machine : Starting the main run loop.
2025-10-11 18:28:39,821 : INFO : Machine : Shutting down...
2025-10-11 18:28:39,821 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-11 18:28:40,833 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 111, in process_widget
    self.machine.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Show "super_jets_startup" >> Failed to load config player super_jets_startup:slides with settings {'super_jets_startup': {'widgets': [{'type': 'text', 'text': 'SUPER JETS', 'font_size': 20, 'y': '60%', 'priority': 200, '_default_settings': ['type', 'text', 'font_size', 'y', 'priority']}], 'target': None, 'background_color': [0.0, 0.0, 0.0, 1.0], 'priority': None, 'show': True, 'force': False, 'expire': None, 'slide': None, 'tokens': {}, 'action': 'play'}} >> Your config contains a value for the setting "widgets:text:widgets:text:priority", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-11 18:28:43,053 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 111, in process_widget
    self.machine.config_validator.validate_config('widgets:{}'.format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Show "super_jets_startup" >> Failed to load config player super_jets_startup:slides with settings {'super_jets_startup': {'widgets': [{'type': 'text', 'text': 'SUPER JETS', 'font_size': 20, 'y': '60%', 'priority': 200, '_default_settings': ['type', 'text', 'font_size', 'y', 'priority']}], 'target': None, 'background_color': [0.0, 0.0, 0.0, 1.0], 'priority': None, 'show': True, 'force': False, 'expire': None, 'slide': None, 'tokens': {}, 'action': 'play'}} >> Your config contains a value for the setting "widgets:text:widgets:text:priority", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
