2025-10-12 09:58:30,406 : INFO : root : Loading config.
2025-10-12 09:58:30,410 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-12 09:58:30,411 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\f7776651e259183bd84a8c8d686bf868.mpf_cache
2025-10-12 09:58:30,499 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\70233839fc0b792ce11a62f3c18c1950.mpf_cache
2025-10-12 09:58:30,500 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-12 09:58:30,501 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\67a19b095f918111543419ac0271bfb1.mpf_cache
2025-10-12 09:58:30,502 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\be387b0e8ed00556ec738d83cd6947d1.mpf_cache
2025-10-12 09:58:30,503 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\5a8efabd9666d8c71fa755fc28a9bf1e.mpf_cache
2025-10-12 09:58:30,503 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\fb58745e58584e219ff53db445e8e9f2.mpf_cache
2025-10-12 09:58:30,504 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp7\modes\special\config\special.yaml
2025-10-12 09:58:30,504 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp7\modes\special\config\special.yaml.
2025-10-12 09:58:30,515 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp7\modes\special\config\special.yaml
2025-10-12 09:58:30,516 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\9e788d9ac28f3464b985b20edf80a10e.mpf_cache
2025-10-12 09:58:30,516 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b710dc01437f1dfd05f3b5275f67493b.mpf_cache
2025-10-12 09:58:30,517 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\0a23590f4081187a3ecee75c7657616e.mpf_cache
2025-10-12 09:58:30,518 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\374a5edaf0766cb9005f368df852c09d.mpf_cache
2025-10-12 09:58:30,519 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b50d1c72289d6f8f00cba34766fbb2e5.mpf_cache
2025-10-12 09:58:30,519 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\069a726c379c7a3dc006889318eb30f2.mpf_cache
2025-10-12 09:58:30,520 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\6159dd3e8b071f5aa615e717784124e9.mpf_cache
2025-10-12 09:58:30,521 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-12 09:58:30,521 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-12-09-58-30-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-12 09:58:30,521 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-12 09:58:30,521 : INFO : Machine : Machine path: C:\Users\richa\ttp7
2025-10-12 09:58:30,521 : INFO : Machine : Platform: win32
2025-10-12 09:58:30,521 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-12 09:58:30,521 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-12 09:58:30,523 : INFO : Machine : Initializing MPF...
2025-10-12 09:58:30,893 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,941 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-12 09:58:30,941 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 13201700, 'prev_value': None, 'change': True}
2025-10-12 09:58:30,941 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,941 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,941 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,950 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,950 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,950 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,950 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,951 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-12 09:58:30,951 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-12 09:58:30,952 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tain a dot?')>) at C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tain a dot?')>) at C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 103, in get_event_and_condition_from_string
    additional_priority = int(event_string[priority_start + 1:])
ValueError: invalid literal for int() with base 10: 'counters.TIME_droptargets_counter==3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 119, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 168, in _load_mode
    return mode_class(self.machine, config, mode_string, config['mode']['path'], config['mode']['asset_paths'])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 77, in __init__
    self.configure_mode_settings(config.get('mode', dict()))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 126, in configure_mode_settings
    self.machine.events.add_handler(event=event, handler=self.start,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 231, in add_handler
    event, condition, additional_priority = self.get_event_and_condition_from_string(event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 105, in get_event_and_condition_from_string
    raise ValueError('Failed to parse priority in event name, '
ValueError: Failed to parse priority in event name, please remedy "device.counters.TIME_droptargets_counter==3". Does your event name contain a dot?
2025-10-12 09:58:30,954 : INFO : Machine : Starting the main run loop.
2025-10-12 09:58:30,959 : INFO : Machine : Shutting down...
2025-10-12 09:58:30,959 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-12 09:58:31,972 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 103, in get_event_and_condition_from_string
    additional_priority = int(event_string[priority_start + 1:])
ValueError: invalid literal for int() with base 10: 'counters.TIME_droptargets_counter==3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 119, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 168, in _load_mode
    return mode_class(self.machine, config, mode_string, config['mode']['path'], config['mode']['asset_paths'])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 77, in __init__
    self.configure_mode_settings(config.get('mode', dict()))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 126, in configure_mode_settings
    self.machine.events.add_handler(event=event, handler=self.start,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 231, in add_handler
    event, condition, additional_priority = self.get_event_and_condition_from_string(event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 105, in get_event_and_condition_from_string
    raise ValueError('Failed to parse priority in event name, '
ValueError: Failed to parse priority in event name, please remedy "device.counters.TIME_droptargets_counter==3". Does your event name contain a dot?
2025-10-12 09:58:34,866 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 103, in get_event_and_condition_from_string
    additional_priority = int(event_string[priority_start + 1:])
ValueError: invalid literal for int() with base 10: 'counters.TIME_droptargets_counter==3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 119, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 168, in _load_mode
    return mode_class(self.machine, config, mode_string, config['mode']['path'], config['mode']['asset_paths'])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 77, in __init__
    self.configure_mode_settings(config.get('mode', dict()))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 126, in configure_mode_settings
    self.machine.events.add_handler(event=event, handler=self.start,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 231, in add_handler
    event, condition, additional_priority = self.get_event_and_condition_from_string(event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 105, in get_event_and_condition_from_string
    raise ValueError('Failed to parse priority in event name, '
ValueError: Failed to parse priority in event name, please remedy "device.counters.TIME_droptargets_counter==3". Does your event name contain a dot?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
